#!/bin/bash
# Speaker similarity — episode cloned models vs Hindi reference segments
# Compares voice-cloned TTS output against the Hindi reference used to clone it.
# Models generated by generate_episode_cloned.py using Hindi audio as voice prompt.
# Expected: chatterbox_cloned should score HIGH (same voice as reference)
#           generic TTS models should score LOW
cd /Users/abey/Documents/tts_metrics
echo "Running speaker similarity — cloned episode models vs Hindi reference..."
FORCE_SPEAKER_CPU=1 NUMBA_CACHE_DIR=/tmp/numba conda run -n base python3 gates/gate_speaker_sim.py \
    --models-dir data/hindi_eval/models \
    --ref-dir    data/hindi_eval/reference \
    --output-dir output/hindi_eval/speaker_sim
